name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Ensure Go dependencies
      run: |
        go mod tidy
        go mod verify

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Download required wordlists
      run: |
        curl -o frenchdiceware.txt https://raw.githubusercontent.com/mbelivo/diceware-wordlists-fr/refs/heads/master/wordlist_fr_5d.txt
        curl -o diceware-fr-alt.txt https://raw.githubusercontent.com/ArthurPons/diceware-fr-alt/refs/heads/master/diceware-fr-alt.txt

    - name: Build
      run: make build

    - name: Run tests
      run: make test

    - name: Security scan
      uses: securego/gosec@master
      with:
        args: ./...

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Ensure Go dependencies
      run: |
        go mod tidy
        go mod verify

    - name: Download required wordlists
      run: |
        curl -o frenchdiceware.txt https://raw.githubusercontent.com/mbelivo/diceware-wordlists-fr/refs/heads/master/wordlist_fr_5d.txt
        curl -o diceware-fr-alt.txt https://raw.githubusercontent.com/ArthurPons/diceware-fr-alt/refs/heads/master/diceware-fr-alt.txt

    - name: Build and push container
      run: |
        podman build -t diceware .
        # Add container registry push here if needed

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          diceware
          LICENSE
          README.md
